export const RUNES_MAP = {
  "Lesser Mark of Attack Damage": ["5001"],
  "Lesser Mark of Scaling Attack Damage": ["5002"],
  "Lesser Mark of Attack Speed": ["5003"],
  "Lesser Mark of Critical Damage": ["5005"],
  "Lesser Mark of Critical Chance": ["5007"],
  "Lesser Mark of Lethality": ["5009"],
  "Lesser Mark of Health": ["5011"],
  "Lesser Mark of Scaling Health": ["5012"],
  "Lesser Mark of Armor": ["5013"],
  "Lesser Mark of Magic Resist": ["5015"],
  "Lesser Mark of Scaling Magic Resist": ["5016"],
  "Lesser Mark of Cooldown Reduction": ["5021"],
  "Lesser Mark of Ability Power": ["5023"],
  "Lesser Mark of Scaling Ability Power": ["5024"],
  "Lesser Mark of Mana": ["5025"],
  "Lesser Mark of Scaling Mana": ["5026"],
  "Lesser Mark of Mana Regeneration": ["5027"],
  "Lesser Mark of Magic Penetration": ["5029"],
  "Lesser Glyph of Attack Damage": ["5031"],
  "Lesser Glyph of Scaling Attack Damage": ["5032"],
  "Lesser Glyph of Attack Speed": ["5033"],
  "Lesser Glyph of Critical Damage": ["5035"],
  "Lesser Glyph of Critical Chance": ["5037"],
  "Lesser Glyph of Health": ["5041"],
  "Lesser Glyph of Scaling Health": ["5042"],
  "Lesser Glyph of Armor": ["5043"],
  "Lesser Glyph of Magic Resist": ["5045"],
  "Lesser Glyph of Scaling Magic Resist": ["5046"],
  "Lesser Glyph of Health Regeneration": ["5047"],
  "Lesser Glyph of Cooldown Reduction": ["5051"],
  "Lesser Glyph of Scaling Cooldown Reduction": ["5052"],
  "Lesser Glyph of Ability Power": ["5053"],
  "Lesser Glyph of Scaling Ability Power": ["5054"],
  "Lesser Glyph of Mana": ["5055"],
  "Lesser Glyph of Scaling Mana": ["5056"],
  "Lesser Glyph of Mana Regeneration": ["5057"],
  "Lesser Glyph of Scaling Mana Regeneration": ["5058"],
  "Lesser Glyph of Magic Penetration": ["5059"],
  "Lesser Seal of Attack Damage": ["5061"],
  "Lesser Seal of Scaling Attack Damage": ["5062"],
  "Lesser Seal of Attack Speed": ["5063"],
  "Lesser Seal of Critical Damage": ["5065"],
  "Lesser Seal of Critical Chance": ["5067"],
  "Lesser Seal of Health": ["5071"],
  "Lesser Seal of Scaling Health": ["5072"],
  "Lesser Seal of Armor": ["5073"],
  "Lesser Seal of Scaling Armor": ["5074"],
  "Lesser Seal of Magic Resist": ["5075"],
  "Lesser Seal of Scaling Magic Resist": ["5076"],
  "Lesser Seal of Health Regeneration": ["5077"],
  "Lesser Seal of Scaling Health Regeneration": ["5078"],
  "Lesser Seal of Cooldown Reduction": ["5081"],
  "Lesser Seal of Ability Power": ["5083"],
  "Lesser Seal of Scaling Ability Power": ["5084"],
  "Lesser Seal of Mana": ["5085"],
  "Lesser Seal of Scaling Mana": ["5086"],
  "Lesser Seal of Mana Regeneration": ["5087"],
  "Lesser Seal of Scaling Mana Regeneration": ["5088"],
  "Lesser Quintessence of Attack Damage": ["5091"],
  "Lesser Quintessence of Scaling Attack Damage": ["5092"],
  "Lesser Quintessence of Attack Speed": ["5093"],
  "Lesser Quintessence of Critical Damage": ["5095"],
  "Lesser Quintessence of Critical Chance": ["5097"],
  "Lesser Quintessence of Lethality": ["5099"],
  "Lesser Quintessence of Health": ["5101"],
  "Lesser Quintessence of Scaling Health": ["5102"],
  "Lesser Quintessence of Armor": ["5103"],
  "Lesser Quintessence of Scaling Armor": ["5104"],
  "Lesser Quintessence of Magic Resist": ["5105"],
  "Lesser Quintessence of Scaling Magic Resist": ["5106"],
  "Lesser Quintessence of Health Regeneration": ["5107"],
  "Lesser Quintessence of Scaling Health Regeneration": ["5108"],
  "Lesser Quintessence of Cooldown Reduction": ["5111"],
  "Lesser Quintessence of Scaling Cooldown Reduction": ["5112"],
  "Lesser Quintessence of Ability Power": ["5113"],
  "Lesser Quintessence of Scaling Ability Power": ["5114"],
  "Lesser Quintessence of Mana": ["5115"],
  "Lesser Quintessence of Scaling Mana": ["5116"],
  "Lesser Quintessence of Mana Regeneration": ["5117"],
  "Lesser Quintessence of Scaling Mana Regeneration": ["5118"],
  "Lesser Quintessence of Magic Penetration": ["5119"],
  "Lesser Quintessence of Movement Speed": ["5121"],
  "Mark of Attack Damage": ["5123"],
  "Mark of Scaling Attack Damage": ["5124"],
  "Mark of Attack Speed": ["5125"],
  "Mark of Critical Damage": ["5127"],
  "Mark of Critical Chance": ["5129"],
  "Mark of Lethality": ["5131"],
  "Mark of Health": ["5133"],
  "Mark of Scaling Health": ["5134"],
  "Mark of Armor": ["5135"],
  "Mark of Magic Resist": ["5137"],
  "Mark of Scaling Magic Resist": ["5138"],
  "Mark of Cooldown Reduction": ["5143"],
  "Mark of Ability Power": ["5145"],
  "Mark of Scaling Ability Power": ["5146"],
  "Mark of Mana": ["5147"],
  "Mark of Scaling Mana": ["5148"],
  "Mark of Mana Regeneration": ["5149"],
  "Mark of Magic Penetration": ["5151"],
  "Glyph of Attack Damage": ["5153"],
  "Glyph of Scaling Attack Damage": ["5154"],
  "Glyph of Attack Speed": ["5155"],
  "Glyph of Critical Damage": ["5157"],
  "Glyph of Critical Chance": ["5159"],
  "Glyph of Health": ["5163"],
  "Glyph of Scaling Health": ["5164"],
  "Glyph of Armor": ["5165"],
  "Glyph of Magic Resist": ["5167"],
  "Glyph of Scaling Magic Resist": ["5168"],
  "Glyph of Health Regeneration": ["5169"],
  "Glyph of Cooldown Reduction": ["5173"],
  "Glyph of Scaling Cooldown Reduction": ["5174"],
  "Glyph of Ability Power": ["5175"],
  "Glyph of Scaling Ability Power": ["5176"],
  "Glyph of Mana": ["5177"],
  "Glyph of Scaling Mana": ["5178"],
  "Glyph of Mana Regeneration": ["5179"],
  "Glyph of Scaling Mana Regeneration": ["5180"],
  "Glyph of Magic Penetration": ["5181"],
  "Seal of Attack Damage": ["5183"],
  "Seal of Scaling Attack Damage": ["5184"],
  "Seal of Attack Speed": ["5185"],
  "Seal of Critical Damage": ["5187"],
  "Seal of Critical Chance": ["5189"],
  "Seal of Health": ["5193"],
  "Seal of Scaling Health": ["5194"],
  "Seal of Armor": ["5195"],
  "Seal of Scaling Armor": ["5196"],
  "Seal of Magic Resist": ["5197"],
  "Seal of Scaling Magic Resist": ["5198"],
  "Seal of Health Regeneration": ["5199"],
  "Seal of Scaling Health Regeneration": ["5200"],
  "Seal of Cooldown Reduction": ["5203"],
  "Seal of Ability Power": ["5205"],
  "Seal of Scaling Ability Power": ["5206"],
  "Seal of Mana": ["5207"],
  "Seal of Scaling Mana": ["5208"],
  "Seal of Mana Regeneration": ["5209"],
  "Seal of Scaling Mana Regeneration": ["5210"],
  "Quintessence of Attack Damage": ["5213"],
  "Quintessence of Scaling Attack Damage": ["5214"],
  "Quintessence of Attack Speed": ["5215"],
  "Quintessence of Critical Damage": ["5217"],
  "Quintessence of Critical Chance": ["5219"],
  "Quintessence of Lethality": ["5221"],
  "Quintessence of Health": ["5223"],
  "Quintessence of Scaling Health": ["5224"],
  "Quintessence of Armor": ["5225"],
  "Quintessence of Scaling Armor": ["5226"],
  "Quintessence of Magic Resist": ["5227"],
  "Quintessence of Scaling Magic Resist": ["5228"],
  "Quintessence of Health Regeneration": ["5229"],
  "Quintessence of Scaling Health Regeneration": ["5230"],
  "Quintessence of Cooldown Reduction": ["5233"],
  "Quintessence of Scaling Cooldown Reduction": ["5234"],
  "Quintessence of Ability Power": ["5235"],
  "Quintessence of Scaling Ability Power": ["5236"],
  "Quintessence of Mana": ["5237"],
  "Quintessence of Scaling Mana": ["5238"],
  "Quintessence of Mana Regeneration": ["5239"],
  "Quintessence of Scaling Mana Regeneration": ["5240"],
  "Quintessence of Magic Penetration": ["5241"],
  "Quintessence of Movement Speed": ["5243"],
  "Greater Mark of Attack Damage": ["5245"],
  "Greater Mark of Scaling Attack Damage": ["5246"],
  "Greater Mark of Attack Speed": ["5247"],
  "Greater Mark of Critical Damage": ["5249"],
  "Greater Mark of Critical Chance": ["5251"],
  "Greater Mark of Lethality": ["5253"],
  "Greater Mark of Health": ["5255"],
  "Greater Mark of Scaling Health": ["5256"],
  "Greater Mark of Armor": ["5257"],
  "Greater Mark of Magic Resist": ["5259"],
  "Greater Mark of Scaling Magic Resist": ["5260"],
  "Greater Mark of Cooldown Reduction": ["5265"],
  "Greater Mark of Ability Power": ["5267"],
  "Greater Mark of Scaling Ability Power": ["5268"],
  "Greater Mark of Mana": ["5269"],
  "Greater Mark of Scaling Mana": ["5270"],
  "Greater Mark of Mana Regeneration": ["5271"],
  "Greater Mark of Magic Penetration": ["5273"],
  "Greater Glyph of Attack Damage": ["5275"],
  "Greater Glyph of Scaling Attack Damage": ["5276"],
  "Greater Glyph of Attack Speed": ["5277"],
  "Greater Glyph of Critical Damage": ["5279"],
  "Greater Glyph of Critical Chance": ["5281"],
  "Greater Glyph of Health": ["5285"],
  "Greater Glyph of Scaling Health": ["5286"],
  "Greater Glyph of Armor": ["5287"],
  "Greater Glyph of Magic Resist": ["5289"],
  "Greater Glyph of Scaling Magic Resist": ["5290"],
  "Greater Glyph of Health Regeneration": ["5291"],
  "Greater Glyph of Cooldown Reduction": ["5295"],
  "Greater Glyph of Scaling Cooldown Reduction": ["5296"],
  "Greater Glyph of Ability Power": ["5297"],
  "Greater Glyph of Scaling Ability Power": ["5298"],
  "Greater Glyph of Mana": ["5299"],
  "Greater Glyph of Scaling Mana": ["5300"],
  "Greater Glyph of Mana Regeneration": ["5301"],
  "Greater Glyph of Scaling Mana Regeneration": ["5302"],
  "Greater Glyph of Magic Penetration": ["5303"],
  "Greater Seal of Attack Damage": ["5305"],
  "Greater Seal of Scaling Attack Damage": ["5306"],
  "Greater Seal of Attack Speed": ["5307"],
  "Greater Seal of Critical Damage": ["5309"],
  "Greater Seal of Critical Chance": ["5311"],
  "Greater Seal of Health": ["5315"],
  "Greater Seal of Scaling Health": ["5316"],
  "Greater Seal of Armor": ["5317"],
  "Greater Seal of Scaling Armor": ["5318"],
  "Greater Seal of Magic Resist": ["5319"],
  "Greater Seal of Scaling Magic Resist": ["5320"],
  "Greater Seal of Health Regeneration": ["5321"],
  "Greater Seal of Scaling Health Regeneration": ["5322"],
  "Greater Seal of Cooldown Reduction": ["5325"],
  "Greater Seal of Ability Power": ["5327"],
  "Greater Seal of Scaling Ability Power": ["5328"],
  "Greater Seal of Mana": ["5329"],
  "Greater Seal of Scaling Mana": ["5330"],
  "Greater Seal of Mana Regeneration": ["5331"],
  "Greater Seal of Scaling Mana Regeneration": ["5332"],
  "Greater Quintessence of Attack Damage": ["5335"],
  "Greater Quintessence of Scaling Attack Damage": ["5336"],
  "Greater Quintessence of Attack Speed": ["5337"],
  "Greater Quintessence of Critical Damage": ["5339"],
  "Greater Quintessence of Critical Chance": ["5341"],
  "Greater Quintessence of Lethality": ["5343"],
  "Greater Quintessence of Health": ["5345"],
  "Greater Quintessence of Scaling Health": ["5346"],
  "Greater Quintessence of Armor": ["5347"],
  "Greater Quintessence of Scaling Armor": ["5348"],
  "Greater Quintessence of Magic Resist": ["5349"],
  "Greater Quintessence of Scaling Magic Resist": ["5350"],
  "Greater Quintessence of Health Regeneration": ["5351"],
  "Greater Quintessence of Scaling Health Regeneration": ["5352"],
  "Greater Quintessence of Cooldown Reduction": ["5355"],
  "Greater Quintessence of Scaling Cooldown Reduction": ["5356"],
  "Greater Quintessence of Ability Power": ["5357"],
  "Greater Quintessence of Scaling Ability Power": ["5358"],
  "Greater Quintessence of Mana": ["5359"],
  "Greater Quintessence of Scaling Mana": ["5360"],
  "Greater Quintessence of Mana Regeneration": ["5361"],
  "Greater Quintessence of Scaling Mana Regeneration": ["5362"],
  "Greater Quintessence of Magic Penetration": ["5363"],
  "Greater Quintessence of Movement Speed": ["5365"],
  "Greater Quintessence of Revival": ["5366"],
  "Greater Quintessence of Gold": ["5367"],
  "Greater Quintessence of Experience": ["5368"],
  "Greater Seal of Energy Regeneration": ["5369"],
  "Greater Seal of Scaling Energy Regeneration": ["5370"],
  "Greater Glyph of Energy": ["5371"],
  "Greater Glyph of Scaling Energy": ["5372"],
  "Greater Quintessence of Energy Regeneration": ["5373"],
  "Greater Quintessence of Energy": ["5374"],
  "Lesser Mark of Precision": ["5400"],
  "Mark of Precision": ["5401"],
  "Greater Mark of Precision": ["5402"],
  "Greater Seal of Gold": ["5403"],
  "Lesser Quintessence of Percent Health": ["5404"],
  "Quintessence of Percent Health": ["5405"],
  "Greater Quintessence of Percent Health": ["5406"],
  "Lesser Quintessence of Spell Vamp": ["5407"],
  "Quintessence of Spell Vamp": ["5408"],
  "Greater Quintessence of Spell Vamp": ["5409"],
  "Lesser Quintessence of Life Steal": ["5410"],
  "Quintessence of Life Steal": ["5411"],
  "Greater Quintessence of Life Steal": ["5412"],
  "Lesser Seal of Percent Health": ["5413"],
  "Seal of Percent Health": ["5414"],
  "Greater Seal of Percent Health": ["5415"],
  "Lesser Quintessence of Precision": ["5416"],
  "Quintessence of Precision": ["5417"],
  "Greater Quintessence of Precision": ["5418"],
  "Mark of the Crippling Candy Cane": ["8001"],
  "Lesser Mark of the Yuletide Tannenbaum ": ["8002"],
  "Glyph of the Special Stocking": ["8003"],
  "Lesser Glyph of the Gracious Gift": ["8005"],
  "Lesser Seal of the Stout Snowman": ["8006"],
  "Lesser Mark of Alpine Attack Speed": ["8007"],
  "Mark of the Combatant": ["8008"],
  "Lesser Seal of the Medalist": ["8009"],
  "Lesser Glyph of the Challenger": ["8011"],
  "Glyph of the Soaring Slalom": ["8012"],
  "Quintessence of the Headless Horseman": ["8013"],
  "Quintessence of the Piercing Screech": ["8014"],
  "Quintessence of Bountiful Treats": ["8015"],
  "Quintessence of the Speedy Specter": ["8016"],
  "Quintessence of the Witches Brew": ["8017"],
  "Greater Quintessence of the Piercing Present": ["8019"],
  "Greater Quintessence of the Deadly Wreath": ["8020"],
  "Greater Quintessence of Frosty Health": ["8021"],
  "Greater Quintessence of Sugar Rush": ["8022"],
  "Greater Quintessence of Studio Rumble": ["8035"],
  "Razer Mark of Precision": ["10001"],
  "Razer Quintessence of Speed": ["10002"]
};
